### ISSUE TITLE
Missing modules: Commerce_product_reference_ui

### ISSUE THREAD

**Issue by paat** [rszrama/commercedev#1]
During install of Drupal 7.0 (2011-Jan-05) I get the following error:
Error
    Required modules    Required modules not found.
The following modules are required but were not found. Move them into the appropriate modules subdirectory, such as sites/all/modules. Missing modules: Commerce_product_reference_ui

I had all the required modules in sites/all/modules:
addressfield  admin_menu  commerce  ctools  entity  README.txt  rules  views

all modules are up-to-date (9th Jan 2011)

**Comment by paat** [comment]
Seems that commenting out 
dependencies[] = commerce_product_reference_ui in file commercedev.info
resolved the problem.

**Comment by rszrama** [comment]
You just need to get the latest version of the Commerce modules; it's in there.
